/* Action Inbox — 11 sample cases across TechOps · Procurement · Finance.
   Plain data (no JSX). brain = the company-brain access layer per case. */
export const CASES = [
  {
    id: 'ACT-1049', tab: 'ACT-1049 Unlock Okta fo…', dot: 'pending', domain: 'TechOps',
    title: 'Unlock Okta for Priya N. after MFA recovery',
    summary: 'I can unlock the account and require a password reset on next sign-in.',
    hold: 'Confidence 91% — held for operator approval.',
    path: ['TechOps agent', 'zendesk', 'priya nair', 'act-1049', 'awaiting you'],
    verb: 'APPROVE', verbKey: 'A', timer: '8h 11m', confidence: 91, state: 'needs', updated: '2m ago', updatedPct: 92, slaPct: 32, arrival: 1,
    quote: { initials: 'PN', name: 'Priya Nair', via: 'Zendesk', route: 'TechOps agent', status: 'waiting for you', body: 'Priya is locked out after a device migration. The ticket includes manager confirmation and a current Iru device match.' },
    why: ['Confidence below the auto-run threshold for identity writes', 'Action touches a production system of record', 'Requester recently changed devices'],
    sources: '6 examined',
    sourcesDetail: ['okta employee record · iru device inventory', 'zendesk ZD-7782 · slack #it-help thread', 'HR roster · prior case TKT-4776'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Approve & run', desc: 'Requester identity matches the employee record and active device inventory.', keys: '↵' },
      { kind: 'Variant', title: 'Approve, then post the standard reset note.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Ask for a second manager check.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #okta · #slack · #zendesk — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Role', value: 'Software Engineer', source: 'okta' },
        { label: 'Dept', value: 'Engineering', source: 'okta' },
        { label: 'Manager', value: 'Leah Chen', source: 'okta' },
        { label: 'Tenure', value: 'Since May 2024', source: 'ragnar', extra: 'recall', tone: 'live' },
      ],
      roster: [
        { name: 'Priya Nair', meta: 'Software Engineer · Engineering', tag: 'Requester', source: 'okta' },
        { name: 'Leah Chen', meta: 'Manager · confirmed the unlock', source: 'okta' },
      ],
      devices: [{ name: 'MacBook Pro 14"', meta: 'P-442 · Iru compliant · migrated today', source: 'Iru' }],
      apps: [
        { name: 'Okta', meta: 'MFA recovery active', source: 'Okta' },
        { name: 'Zendesk', meta: 'ticket ZD-7782', source: 'Zendesk' },
      ],
      scope: 'Unlock account · require password reset · SLA 22m remaining',
      prior: [
        { id: 'TKT-4776', title: 'Device migration for Priya N.', meta: 'resolved yesterday · zendesk' },
        { id: 'TKT-4744', title: 'MFA recovery fallback approval', meta: 'resolved 3w ago · zendesk' },
      ],
    },
    conversation: [
      { author: 'Priya Nair', role: 'requester', time: '07:58', body: "I'm locked out of Okta after the laptop swap — MFA won't accept the new device.", artifacts: [{ kind: 'image', name: 'okta-error.png', meta: 'screenshot' }] },
      { author: 'TechOps agent', role: 'agent', time: '08:00', body: 'I see the device migration completed this morning and the new MacBook is Iru-compliant. Checking the MFA recovery state.' },
      { author: 'Priya Nair', role: 'requester', time: '08:01', body: 'Leah already confirmed on the ticket. Attaching the migration log just in case.', artifacts: [{ kind: 'file', name: 'device-migration-log.txt', meta: 'TXT · 14KB' }] },
      { author: 'TechOps agent', role: 'agent', time: '08:02', body: 'Identity and device match, manager confirmed. Unlocking touches a production identity system, so I\u2019m handing this to an operator for approval.' },
    ],
    discussion: [
      { author: 'Leah Chen', tag: 'manager', time: '1h ago', body: 'Confirmed — Priya swapped laptops yesterday. Fine to unlock.', replies: [
        { author: 'Dana Mol', tag: 'security', time: '52m ago', body: 'No open incidents on that account. Clear from our side — but check MFA re-enrollment happened on the new device before unlocking.', replies: [
          { author: 'TechOps agent', tag: 'agent', time: '50m ago', body: 'Checked: MFA re-enrollment completed 07:44 on P-442, which passed Iru posture at 07:41. If approved, I unlock and force a password reset on next sign-in.', ctx: { to: 'Dana Mol — MFA re-enrollment caveat', read: ['this branch · 2 comments', 'okta MFA log', 'PB-112 step 4'] }, replies: [
            { author: 'Dana Mol', tag: 'security', time: '41m ago', body: 'Does the forced reset also revoke active sessions, or just rotate the password?', replies: [
              { author: 'TechOps agent', tag: 'agent', time: '40m ago', body: 'Both. Policy v14 \u00A76 revokes all sessions on forced reset — Priya\u2019s two active sessions drop, and only the enrolled device keeps MFA.', ctx: { to: 'Dana Mol — session revocation question', read: ['this question only', 'okta session table', 'policy v14 \u00A76'] } },
            ] },
          ] },
        ] },
      ] },
    ],
    brain: {
      reads: [
        { label: 'Identity graph', value: 'Priya Nair ↔ Okta record, match 100%', source: 'okta · 30s' },
        { label: 'Device posture', value: 'P-442 Iru-compliant, migrated 07:41', source: 'iru · 30s' },
        { label: 'Approval chain', value: 'Leah Chen may approve unlocks for Eng', source: 'world model · recall' },
        { label: 'Event history', value: 'TKT-4776 device migration, resolved', source: 'event log' },
        { label: 'Policy', value: 'Identity writes always hold < 95%', source: 'policy · v14' },
      ],
      playbook: { id: 'PB-112', name: 'MFA recovery unlock', origin: 'learned from 63 traces · zero hand-written', success: '96% verified', steps: [
        { label: 'Verify identity against record', state: 'done' },
        { label: 'Check device posture (Iru)', state: 'done' },
        { label: 'Confirm manager approval', state: 'done' },
        { label: 'Unlock account', state: 'held' },
        { label: 'Require password reset', state: 'pending' },
        { label: 'Post reset note to requester', state: 'pending' },
      ]},
      route: { model: 'Claude Sonnet', path: 'GCP Vertex · europe-west4', reason: 'identity write — frontier passes the PerkBench gate on this task class', cost: '$0.11 / verified outcome', tokens: '12.4K tokens' },
      boundary: {
        sent: ['role: software engineer · team: engineering', 'playbook steps 3–5 · manager approved', 'decision request: approve or escalate'],
        withheld: ['name, org graph, event history', '412 other playbooks', 'reward definitions & private evals'],
        provider: 'Anthropic via Vertex — lab never sees traffic', retention: 'zero-retention posture · logged', ledger: 'LG-30412',
      },
      writes: [
        { on: 'Approve ↵', signal: 'reinforces PB-112 · nudges identity-unlock threshold up' },
        { on: 'Variant ⌥1', signal: 'drafts a reset-note branch in PB-112' },
        { on: 'Alternative / dismiss', signal: 'negative signal → new eval case in PerkBench' },
      ],
    },
  },
  {
    id: 'ACT-1050', tab: 'ACT-1050 Grant contract…', dot: 'warn', domain: 'TechOps',
    title: 'Grant contractor Figma viewer access for Brand sprint',
    summary: 'I can grant viewer-only access scoped to the Brand-sprint project, expiring in 14 days.',
    hold: 'Confidence 84% — external account, held for approval.',
    path: ['Access agent', 'slack', 'marta kline', 'act-1050', 'awaiting you'],
    verb: 'APPROVE', verbKey: 'A', timer: '41h 2m', confidence: 84, state: 'needs', updated: '18m ago', updatedPct: 64, slaPct: 78, arrival: 2,
    quote: { initials: 'MK', name: 'Marta Kline', via: 'Slack', route: 'Access agent', status: 'waiting for you', body: 'Marta needs the contractor from Studio Norr to see the Brand sprint files. Contract runs through the end of the month.' },
    why: ['External collaborator on a company resource', 'No standing grant policy covers agencies', 'Expiry date inferred, not confirmed'],
    sources: '4 examined',
    sourcesDetail: ['figma org directory · slack #brand-sprint thread', 'vendor contract record', 'access policy doc'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Approve & run', desc: 'Viewer-only, project-scoped, time-boxed to the contract window.', keys: '↵' },
      { kind: 'Variant', title: 'Approve, but expire at contract end (18 days).', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Route to design ops for a standing agency policy.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #figma · #slack — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Role', value: 'Brand Lead', source: 'okta' },
        { label: 'Vendor', value: 'Studio Norr · active contract', source: 'ragnar', extra: 'recall', tone: 'live' },
      ],
      roster: [
        { name: 'Marta Kline', meta: 'Brand Lead · Marketing', tag: 'Requester', source: 'okta' },
        { name: 'E. Laurent', meta: 'Contractor · Studio Norr', source: 'figma' },
      ],
      devices: [],
      apps: [
        { name: 'Figma', meta: 'org has 2 open guest seats', source: 'Figma' },
        { name: 'Slack', meta: '#brand-sprint thread', source: 'Slack' },
      ],
      scope: 'Grant viewer · project-scoped · expiring · SLA 3h remaining',
      prior: [{ id: 'ACT-0981', title: 'Agency viewer grant for Q1 refresh', meta: 'approved 2mo ago · figma' }],
    },
    conversation: [
      { author: 'Marta Kline', role: 'requester', time: '11:20', body: 'The Studio Norr contractor needs to see the Brand sprint files — contract runs through month end.', artifacts: [{ kind: 'link', name: 'brand-sprint', meta: 'figma' }] },
      { author: 'Access agent', role: 'agent', time: '11:22', body: 'No standing policy covers agency guests, and the expiry is inferred from the contract record — handing to an operator with a scoped, time-boxed proposal.' },
    ],
    discussion: [],
    brain: {
      reads: [
        { label: 'Vendor record', value: 'Studio Norr · contract through Jul 31', source: 'world model · recall' },
        { label: 'Guest seats', value: 'Figma org: 2 of 10 free', source: 'figma · 2m' },
        { label: 'Grant history', value: 'ACT-0981 agency viewer grant, clean', source: 'event log' },
        { label: 'Policy gap', value: 'No standing rule for agency guests', source: 'policy · v14' },
      ],
      playbook: { id: 'PB-207', name: 'External viewer grant', origin: 'learned from 21 traces', success: '94% verified', steps: [
        { label: 'Resolve requester authority', state: 'done' },
        { label: 'Match vendor to active contract', state: 'done' },
        { label: 'Scope to project, time-box', state: 'done' },
        { label: 'Grant viewer seat', state: 'held' },
        { label: 'Schedule expiry + revoke', state: 'pending' },
      ]},
      route: { model: 'Owned adapter A-3 (open weights)', path: 'in-boundary · customer VPC', reason: 'grant-scoping beats frontier on this class at 1/40th the cost', cost: '$0.003 / verified outcome', tokens: '3.1K tokens' },
      boundary: {
        sent: ['nothing crossed — in-boundary route', 'external email domain only, for seat match'],
        withheld: ['contract terms & rates', 'org directory', 'all playbooks & evals'],
        provider: 'none — sovereign inference', retention: 'n/a · logged', ledger: 'LG-30455',
      },
      writes: [
        { on: 'Approve ↵', signal: 'reinforces PB-207 scoping pattern' },
        { on: 'Variant ⌥1', signal: 'teaches contract-end expiry as default' },
        { on: 'Alternative ⌥2', signal: 'flags policy gap → drafts standing agency rule' },
      ],
    },
  },
  {
    id: 'ACT-1053', tab: 'ACT-1053 Revoke GitHub…', dot: 'pending', domain: 'TechOps',
    title: 'Revoke GitHub access for departed contractor Tomas V.',
    summary: 'Off-boarding shows Tomas departed Friday; his PAT is still active. I can revoke org access and rotate the affected deploy key.',
    hold: 'Confidence 88% — destructive action, held for approval.',
    path: ['Security agent', 'slack', 'dana mol', 'act-1053', 'awaiting you'],
    verb: 'APPROVE', verbKey: 'A', timer: '2h 44m', confidence: 88, state: 'needs', updated: '45s ago', updatedPct: 97, slaPct: 12, arrival: 3,
    quote: { initials: 'DM', name: 'Dana Mol', via: 'Slack', route: 'Security agent', status: 'waiting for you', body: 'Off-boarding checklist flagged an active GitHub token for a contractor who left on Friday. Access should be gone already.' },
    why: ['Destructive, hard-to-reverse action', 'Deploy key rotation touches CI', 'Account shows a commit 2 hours ago that needs a look'],
    sources: '5 examined',
    sourcesDetail: ['github org audit log · CI deploy-key registry', 'HR off-boarding record', 'slack #security · vendor roster'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Approve & run', desc: 'Departure confirmed by HR record; token activity is automated CI, not human.', keys: '↵' },
      { kind: 'Variant', title: 'Revoke access now, rotate the key in the maintenance window.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Escalate to security on-call for the recent commit.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #github · #slack — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Status', value: 'Departed · off-boarded Friday', source: 'okta' },
        { label: 'Access', value: 'GitHub org member + PAT', source: 'github' },
      ],
      roster: [
        { name: 'Dana Mol', meta: 'Security Ops', tag: 'Requester', source: 'okta' },
        { name: 'Tomas V.', meta: 'Contractor · departed Fri', source: 'github' },
      ],
      devices: [],
      apps: [
        { name: 'GitHub', meta: 'last activity 2h ago (CI)', source: 'GitHub' },
        { name: 'CI', meta: 'deploy key ci-prod-2', source: 'GitHub' },
      ],
      scope: 'Revoke org access · rotate deploy key · SLA 15m remaining',
      prior: [{ id: 'ACT-0912', title: 'Contractor off-board revoke (batch)', meta: 'approved 1mo ago · github' }],
    },
    conversation: [
      { author: 'Dana Mol', role: 'requester', time: '09:14', body: 'Off-boarding checklist flagged an active GitHub PAT for Tomas V., who left Friday.', artifacts: [{ kind: 'file', name: 'offboard-audit.csv', meta: 'CSV · 3KB' }] },
      { author: 'Security agent', role: 'agent', time: '09:15', body: 'Access revocation plus deploy-key rotation is destructive and touches CI — holding for operator approval. The 2h-ago commit is automated CI activity.' },
    ],
    discussion: [{ author: 'Dana Mol', tag: 'security', time: '20m ago', body: 'Rotate ci-prod-2 in the same change, please — it was in his scope.' }],
    brain: {
      reads: [
        { label: 'Off-boarding record', value: 'Tomas V. departed Fri · HR confirmed', source: 'hibob · 5m' },
        { label: 'Audit log', value: 'PAT active · last commit = CI bot', source: 'github · 45s' },
        { label: 'Blast radius', value: 'ci-prod-2 used by 3 pipelines', source: 'world model · recall' },
        { label: 'Prior pattern', value: 'ACT-0912 batch revoke, no incident', source: 'event log' },
      ],
      playbook: { id: 'PB-089', name: 'Departure access revoke', origin: 'learned from 47 traces', success: '98% verified', steps: [
        { label: 'Confirm departure in HR record', state: 'done' },
        { label: 'Enumerate live credentials', state: 'done' },
        { label: 'Classify recent activity', state: 'done' },
        { label: 'Revoke org access + PAT', state: 'held' },
        { label: 'Rotate affected deploy keys', state: 'held' },
        { label: 'Verify pipelines green', state: 'pending' },
      ]},
      route: { model: 'Claude Sonnet', path: 'GCP Vertex · europe-west4', reason: 'destructive class — frontier + hold, per policy', cost: '$0.09 / verified outcome', tokens: '9.8K tokens' },
      boundary: {
        sent: ['role: contractor, departed · anonymized', 'steps 3–5 · security requested', 'decision request: approve or escalate'],
        withheld: ['repo names & code', 'pipeline topology', 'HR record details'],
        provider: 'Anthropic via Vertex — lab never sees traffic', retention: 'zero-retention posture · logged', ledger: 'LG-30461',
      },
      writes: [
        { on: 'Approve ↵', signal: 'reinforces PB-089 · CI-activity classifier +' },
        { on: 'Variant ⌥1', signal: 'teaches maintenance-window preference for key rotation' },
        { on: 'Alternative ⌥2', signal: 'escalation trace → security-review eval case' },
      ],
    },
  },
  {
    id: 'ACT-1052', tab: 'ACT-1052 Release payme…', dot: 'pending', domain: 'Finance',
    title: 'Release payment: Studio Norr invoice differs from PO by $2,400',
    summary: 'Invoice INV-2214 is $2,400 over the PO. I traced the difference to a signed change order for extra brand assets, so I can release payment against the amended total.',
    hold: 'Confidence 86% — money movement, held for approval.',
    path: ['Finance agent', 'netsuite', 'accounts payable', 'act-1052', 'awaiting you'],
    verb: 'RELEASE', verbKey: 'A', timer: '20h 30m', confidence: 86, state: 'needs', updated: '6m ago', updatedPct: 84, slaPct: 55, arrival: 4,
    quote: { initials: 'AP', name: 'AP queue', via: 'NetSuite', route: 'Finance agent', status: 'waiting for you', body: 'Three-way match failed on INV-2214: invoice $14,900 vs PO $12,500. Vendor says a change order covers it.' },
    why: ['Money movement above the $2K auto-release delta', 'Three-way match failed before reconciliation', 'Change order signed by a delegate, not the PO owner'],
    sources: '5 examined',
    sourcesDetail: ['netsuite PO-8841 + INV-2214 · change order CO-112', 'vendor contract record · docusign audit trail'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Release against amended total', desc: 'Change order CO-112 is signed and in scope; delegate had authority that week.', keys: '↵' },
      { kind: 'Variant', title: 'Release the PO amount now, hold the $2,400 pending PO-owner confirmation.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Bounce to the PO owner for re-approval of CO-112.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #netsuite · #slack — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Vendor', value: 'Studio Norr · net-30 · good standing', source: 'ragnar', extra: 'recall', tone: 'live' },
        { label: 'PO owner', value: 'Marta Kline · Marketing', source: 'netsuite' },
        { label: 'Delegate', value: 'J. Ito · signed CO-112 while Marta OOO', source: 'docusign' },
      ],
      roster: [
        { name: 'Marta Kline', meta: 'PO owner · Marketing', source: 'netsuite' },
        { name: 'J. Ito', meta: 'Delegate · signed change order', source: 'docusign' },
      ],
      devices: [],
      apps: [
        { name: 'NetSuite', meta: 'PO-8841 · INV-2214', source: 'NetSuite' },
        { name: 'DocuSign', meta: 'CO-112 · completed', source: 'DocuSign' },
      ],
      scope: 'Release $14,900 · amended PO · SLA 4h remaining',
      prior: [{ id: 'ACT-0997', title: 'Studio Norr milestone payment', meta: 'released 3w ago · netsuite' }],
    },
    conversation: [
      { author: 'AP queue', role: 'requester', time: '10:05', body: 'Three-way match exception: INV-2214 over PO by $2,400.', artifacts: [{ kind: 'file', name: 'INV-2214.pdf', meta: 'PDF · 210KB' }] },
      { author: 'Finance agent', role: 'agent', time: '10:07', body: 'Found change order CO-112 covering extra brand assets, signed by a delegate during the PO owner\u2019s OOO. Amount reconciles exactly. Money movement above the delta threshold — handing to an operator.' },
    ],
    discussion: [],
    brain: {
      reads: [
        { label: 'Three-way match', value: 'PO 12,500 + CO 2,400 = INV 14,900', source: 'netsuite · 6m' },
        { label: 'Delegation rule', value: 'J. Ito held signing authority Jun 22–29', source: 'world model · recall' },
        { label: 'Vendor history', value: '11 invoices, zero disputes', source: 'event log' },
        { label: 'Policy', value: 'Delta > $2K always holds', source: 'policy · v14' },
      ],
      playbook: { id: 'PB-311', name: 'Invoice mismatch reconcile', origin: 'learned from 58 traces', success: '93% verified', steps: [
        { label: 'Run three-way match', state: 'done' },
        { label: 'Search amendments & change orders', state: 'done' },
        { label: 'Verify signature authority', state: 'done' },
        { label: 'Release payment', state: 'held' },
        { label: 'Post reconciliation note', state: 'pending' },
      ]},
      route: { model: 'Claude Sonnet', path: 'GCP Vertex · europe-west4', reason: 'document reasoning over CO terms — frontier wins this class', cost: '$0.14 / verified outcome', tokens: '18.2K tokens' },
      boundary: {
        sent: ['amounts & line-item deltas · vendor anonymized', 'CO-112 clause excerpt', 'decision request: release or hold'],
        withheld: ['vendor identity & rates card', 'full contract', 'payment credentials'],
        provider: 'Anthropic via Vertex — lab never sees traffic', retention: 'zero-retention posture · logged', ledger: 'LG-30470',
      },
      writes: [
        { on: 'Release ↵', signal: 'reinforces PB-311 · delegate-authority check promoted' },
        { on: 'Variant ⌥1', signal: 'teaches split-release pattern for delegate-signed COs' },
        { on: 'Alternative ⌥2', signal: 'tightens re-approval rule → eval case in PerkBench' },
      ],
    },
  },
  {
    id: 'ACT-1051', tab: 'ACT-1051 Zendesk renew…', dot: 'warn', domain: 'Procurement',
    title: 'Renew Zendesk at 78 seats, not 120 — usage supports the cut',
    summary: 'Renewal lands in 12 days. 90-day usage shows 78 active seats of 120 licensed. I can counter at 78 seats with a 2-year lock, saving $31K/yr.',
    hold: 'Confidence 82% — vendor negotiation, held for approval.',
    path: ['Procurement agent', 'netsuite', 'renewals', 'act-1051', 'awaiting you'],
    verb: 'APPROVE', verbKey: 'A', timer: '11d 4h', confidence: 82, state: 'needs', updated: '1h ago', updatedPct: 40, slaPct: 90, arrival: 5,
    quote: { initials: 'RN', name: 'Renewals queue', via: 'NetSuite', route: 'Procurement agent', status: 'waiting for you', body: 'Zendesk auto-renews at 120 seats on Jul 26. Usage has been flat at 76–80 active seats since April.' },
    why: ['Commits the company for 2 years', 'Seat cut could bite if support hiring resumes', 'Vendor counter-offer likely — needs a negotiation mandate'],
    sources: '4 examined',
    sourcesDetail: ['zendesk admin usage export · okta app assignments', 'contract & renewal terms · headcount plan (People)'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Approve counter: 78 seats, 2-yr lock, −$31K/yr', desc: 'Usage is stable; headcount plan adds no support roles this year.', keys: '↵' },
      { kind: 'Variant', title: 'Counter at 90 seats, 1-year term — keeps hiring headroom.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Renew flat, revisit at the next cycle.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #netsuite · #email — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Vendor', value: 'Zendesk · renews Jul 26', source: 'netsuite' },
        { label: 'Usage', value: '78 of 120 seats active (90d)', source: 'ragnar', extra: 'recall', tone: 'live' },
        { label: 'Owner', value: 'IT · budget line OPS-44', source: 'netsuite' },
      ],
      roster: [
        { name: 'Sam Ruiz', meta: 'IT lead · app owner', source: 'okta' },
        { name: 'Zendesk AM', meta: 'vendor account manager', source: 'email' },
      ],
      devices: [],
      apps: [
        { name: 'Zendesk', meta: '120 licensed · 78 active', source: 'Zendesk' },
        { name: 'NetSuite', meta: 'contract C-2210', source: 'NetSuite' },
      ],
      scope: 'Counter-offer · 2-yr commit · $31K/yr delta',
      prior: [{ id: 'ACT-0870', title: 'Slack renewal — seat true-down', meta: 'saved $18K · 4mo ago' }],
    },
    conversation: [
      { author: 'Renewals queue', role: 'requester', time: 'Mon', body: 'Zendesk renewal notice received — auto-renews at current 120 seats.' },
      { author: 'Procurement agent', role: 'agent', time: 'Mon', body: 'Usage supports 78 seats. Drafted a counter with a 2-year lock. Negotiation mandates are operator-approved — handing over.' },
    ],
    discussion: [{ author: 'Sam Ruiz', tag: 'it', time: '2h ago', body: 'No support hiring planned this year — fine to cut, keep 5 spare seats.' }],
    brain: {
      reads: [
        { label: 'Seat usage', value: '78 active / 120 licensed, flat 90d', source: 'zendesk · 1h' },
        { label: 'Headcount plan', value: 'No support roles in FY plan', source: 'world model · recall' },
        { label: 'Negotiation history', value: 'Slack true-down: 2-yr lock won 14% off', source: 'event log' },
        { label: 'Benchmark', value: 'Peer rate $49/seat at this volume', source: 'ragnar · synthesis' },
      ],
      playbook: { id: 'PB-266', name: 'Renewal true-down counter', origin: 'learned from 12 traces', success: '91% verified', steps: [
        { label: 'Pull 90-day usage', state: 'done' },
        { label: 'Cross-check hiring plan', state: 'done' },
        { label: 'Draft counter + term options', state: 'done' },
        { label: 'Send counter to vendor', state: 'held' },
        { label: 'Track response · escalate if flat', state: 'pending' },
      ]},
      route: { model: 'Owned adapter A-7 (open weights)', path: 'in-boundary · customer VPC', reason: 'usage analysis in-boundary; counter drafting verified vs frontier — parity at 1/30th cost', cost: '$0.004 / verified outcome', tokens: '5.6K tokens' },
      boundary: {
        sent: ['nothing crossed — in-boundary route'],
        withheld: ['contract terms & pricing', 'usage data', 'negotiation playbook'],
        provider: 'none — sovereign inference', retention: 'n/a · logged', ledger: 'LG-30474',
      },
      writes: [
        { on: 'Approve ↵', signal: 'reinforces PB-266 · 2-yr-lock pattern promoted' },
        { on: 'Variant ⌥1', signal: 'teaches headroom preference when hiring is uncertain' },
        { on: 'Alternative ⌥2', signal: 'negative signal on true-down aggressiveness' },
      ],
    },
  },
  {
    id: 'ACT-1056', tab: 'ACT-1056 Offsite venue…', dot: 'pending', domain: 'Finance',
    title: 'Expense exception: Platform team offsite venue 18% over policy',
    summary: 'The venue quote is $118/person/night against a $100 cap. Two in-policy venues are unavailable for those dates. I can approve as a documented exception.',
    hold: 'Confidence 79% — policy exception, held for approval.',
    path: ['Finance agent', 'expensify', 'nadia oye', 'act-1056', 'awaiting you'],
    verb: 'APPROVE', verbKey: 'A', timer: '3d 2h', confidence: 79, state: 'needs', updated: '32m ago', updatedPct: 52, slaPct: 70, arrival: 6,
    quote: { initials: 'NO', name: 'Nadia Oye', via: 'Expensify', route: 'Finance agent', status: 'waiting for you', body: 'Booking window closes Friday. The two cheaper venues we used before are fully booked for these dates.' },
    why: ['Explicit policy cap exceeded', 'Exception would set a citable precedent', 'Alternatives checked but not exhaustively'],
    sources: '4 examined',
    sourcesDetail: ['travel policy v6 · expensify pre-approval', 'venue quotes (3) · prior offsite spend'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Approve as documented exception', desc: 'Dates fixed by launch freeze; delta is $612 total; alternatives exhausted for the window.', keys: '↵' },
      { kind: 'Variant', title: 'Approve, tag as one-time — excluded from precedent.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Ask the team to shift dates one week — in-policy venue frees up.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #expensify · #slack — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Requester', value: 'Nadia Oye · EM, Platform', source: 'okta' },
        { label: 'Budget', value: 'Team events: $8.2K remaining', source: 'netsuite' },
      ],
      roster: [
        { name: 'Nadia Oye', meta: 'EM · Platform', tag: 'Requester', source: 'okta' },
      ],
      devices: [],
      apps: [
        { name: 'Expensify', meta: 'pre-approval EXP-5521', source: 'Expensify' },
      ],
      scope: 'Exception +$612 total · 12 people · 3 nights',
      prior: [{ id: 'ACT-0793', title: 'Design offsite exception (+9%)', meta: 'approved 5mo ago · tagged one-time' }],
    },
    conversation: [
      { author: 'Nadia Oye', role: 'requester', time: 'Tue', body: 'Venue quote attached — the usual two places are booked out. Window closes Friday.', artifacts: [{ kind: 'file', name: 'venue-quote.pdf', meta: 'PDF · 96KB' }] },
      { author: 'Finance agent', role: 'agent', time: 'Tue', body: 'Cap is explicit in policy v6, so exceptions are operator-only. Delta is small and documented; two alternatives checked.' },
    ],
    discussion: [],
    brain: {
      reads: [
        { label: 'Policy', value: 'Lodging cap $100/pp/night · v6 §3.2', source: 'policy · v6' },
        { label: 'Budget state', value: 'OPS-51 events: $8.2K remaining', source: 'netsuite · 32m' },
        { label: 'Precedent', value: 'ACT-0793: +9% exception, one-time tag', source: 'event log' },
        { label: 'Calendar', value: 'Launch freeze pins the dates', source: 'world model · recall' },
      ],
      playbook: { id: 'PB-402', name: 'Policy exception review', origin: 'learned from 34 traces', success: '89% verified', steps: [
        { label: 'Quantify the delta vs cap', state: 'done' },
        { label: 'Check alternatives in window', state: 'done' },
        { label: 'Pull precedent cases', state: 'done' },
        { label: 'Approve / decline exception', state: 'held' },
        { label: 'Record precedent tag', state: 'pending' },
      ]},
      route: { model: 'Owned adapter A-3 (open weights)', path: 'in-boundary · customer VPC', reason: 'policy reasoning on owned distribution — passes replay evals', cost: '$0.002 / verified outcome', tokens: '2.4K tokens' },
      boundary: {
        sent: ['nothing crossed — in-boundary route'],
        withheld: ['budget lines', 'employee identities', 'policy corpus'],
        provider: 'none — sovereign inference', retention: 'n/a · logged', ledger: 'LG-30481',
      },
      writes: [
        { on: 'Approve ↵', signal: 'exception precedent recorded, citable' },
        { on: 'Variant ⌥1', signal: 'teaches one-time tagging as the default for small deltas' },
        { on: 'Alternative ⌥2', signal: 'reinforces date-shift as first remedy' },
      ],
    },
  },
  {
    id: 'ACT-1054', tab: 'ACT-1054 New vendor: L…', dot: 'warn', domain: 'Procurement',
    title: 'New vendor request: Linear, 25 seats — overlaps Jira',
    summary: 'Platform wants Linear for sprint tracking. We hold 140 Jira seats at $8.60. I can approve a 90-day scoped pilot for 25 seats, or push consolidation.',
    hold: 'Confidence 74% — new vendor + overlap, held for steering.',
    path: ['Procurement agent', 'slack', 'nadia oye', 'act-1054', 'awaiting you'],
    verb: 'STEER', verbKey: 'S', timer: '5d 12h', confidence: 74, state: 'needs', updated: '3h ago', updatedPct: 30, slaPct: 85, arrival: 7,
    quote: { initials: 'NO', name: 'Nadia Oye', via: 'Slack', route: 'Procurement agent', status: 'waiting for you', body: 'The team is faster in Linear — we prototyped a sprint in the free tier. Can we get 25 seats?' },
    why: ['Tool overlap: Jira contract runs 14 more months', 'New vendor requires security review', 'Team-level preference vs company-level consolidation — a judgement call'],
    sources: '5 examined',
    sourcesDetail: ['jira usage by team · linear SOC2 report', 'jira contract C-1854 · slack #platform thread'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Approve 90-day pilot, 25 seats, exit criteria attached', desc: 'Pilot scoped to Platform; decision point lands before Jira renewal math.', keys: '↵' },
      { kind: 'Variant', title: 'Approve pilot, but require a Jira seat release of 25 in parallel.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Decline — route to the tooling council for a consolidation review.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #slack · #netsuite — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Requester', value: 'Nadia Oye · EM, Platform', source: 'okta' },
        { label: 'Overlap', value: 'Jira: 140 seats · 14mo left', source: 'ragnar', extra: 'recall', tone: 'live' },
      ],
      roster: [
        { name: 'Nadia Oye', meta: 'EM · Platform', tag: 'Requester', source: 'okta' },
        { name: 'Tooling council', meta: 'consolidation owner', source: 'confluence' },
      ],
      devices: [],
      apps: [
        { name: 'Jira', meta: 'Platform usage down 40% QoQ', source: 'Jira' },
        { name: 'Linear', meta: 'SOC2 Type II on file', source: 'Linear' },
      ],
      scope: 'Pilot 25 seats · 90 days · $2.9K',
      prior: [{ id: 'ACT-0654', title: 'Notion pilot → company-wide', meta: 'converted 8mo ago' }],
    },
    conversation: [
      { author: 'Nadia Oye', role: 'requester', time: 'Mon', body: 'Prototyped a sprint in Linear\u2019s free tier — the team is noticeably faster. 25 seats?' },
      { author: 'Procurement agent', role: 'agent', time: 'Mon', body: 'Overlap with Jira is real but Platform\u2019s Jira usage is falling. This is a judgement call between team velocity and consolidation — holding for steering.' },
    ],
    discussion: [],
    brain: {
      reads: [
        { label: 'Usage trend', value: 'Platform Jira activity −40% QoQ', source: 'jira · 3h' },
        { label: 'Contract state', value: 'Jira C-1854 · 14mo remaining', source: 'netsuite' },
        { label: 'Security posture', value: 'Linear SOC2 Type II current', source: 'vendor record' },
        { label: 'Precedent', value: 'Notion pilot → converted, saved $12K', source: 'event log' },
      ],
      playbook: { id: 'PB-271', name: 'New tool pilot gate', origin: 'learned from 9 traces', success: '87% verified', steps: [
        { label: 'Check overlap & contracts', state: 'done' },
        { label: 'Security review (SOC2)', state: 'done' },
        { label: 'Draft pilot with exit criteria', state: 'done' },
        { label: 'Operator steering', state: 'held' },
        { label: 'Provision pilot seats', state: 'pending' },
      ]},
      route: { model: 'Claude Sonnet', path: 'GCP Vertex · europe-west4', reason: 'ambiguous judgement class — frontier + operator steer', cost: '$0.12 / verified outcome', tokens: '14.1K tokens' },
      boundary: {
        sent: ['seat counts & usage deltas · vendors named (public)', 'pilot terms draft', 'decision request: steer'],
        withheld: ['contract pricing', 'team roster', 'consolidation strategy doc'],
        provider: 'Anthropic via Vertex — lab never sees traffic', retention: 'zero-retention posture · logged', ledger: 'LG-30488',
      },
      writes: [
        { on: 'Approve ↵', signal: 'teaches pilot-with-exit-criteria as the overlap default' },
        { on: 'Variant ⌥1', signal: 'teaches seat-release coupling on overlapping pilots' },
        { on: 'Alternative ⌥2', signal: 'strengthens consolidation-first routing' },
      ],
    },
  },
  {
    id: 'ACT-1058', tab: 'ACT-1058 AWS spend +34…', dot: 'warn', domain: 'Finance',
    title: 'AWS spend up 34% MoM — commit to a savings plan?',
    summary: 'June compute spend jumped 34%, driven by the new inference cluster. A 1-year compute savings plan at current baseline would cut ~22%. Waiting on the TAM\u2019s custom-commit quote before this is decision-ready.',
    hold: 'Blocked — 1 of 3 quotes outstanding.',
    path: ['Finance agent', 'aws', 'cloud spend', 'act-1058', 'blocked'],
    verb: 'REVIEW', verbKey: 'R', timer: '9d 0h', confidence: 68, state: 'blocked', updated: '4h ago', updatedPct: 22, slaPct: 95, arrival: 8,
    quote: { initials: 'CS', name: 'Cloud spend monitor', via: 'AWS', route: 'Finance agent', status: 'blocked on vendor', body: 'Anomaly rule fired: compute spend +34% MoM. Root cause is the inference cluster — sustained, not a spike.' },
    why: ['Multi-year commitment with usage uncertainty', 'Phase-3 sovereign inference plan changes the baseline', 'Vendor quote outstanding — decision not yet complete'],
    sources: '6 examined',
    sourcesDetail: ['cost explorer 90d · cluster utilization', 'savings-plan pricing · TAM thread', 'phase-3 capacity plan'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Wait for the TAM quote, then decide (auto-reopens)', desc: 'Committing before the custom quote leaves 4–6% on the table.', keys: '↵' },
      { kind: 'Variant', title: 'Commit now at the public rate — lock 22% immediately.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'No commit — Phase 3 migration makes the baseline unreliable.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #aws · #email — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Driver', value: 'Inference cluster · sustained load', source: 'aws' },
        { label: 'Baseline', value: '$41K/mo compute · +34% MoM', source: 'aws' },
      ],
      roster: [
        { name: 'AWS TAM', meta: 'custom-commit quote pending', source: 'email' },
        { name: 'Infra team', meta: 'cluster owner', source: 'okta' },
      ],
      devices: [],
      apps: [
        { name: 'Cost Explorer', meta: '90-day trend attached', source: 'AWS' },
      ],
      scope: 'Savings plan · ~$108K/yr commit · blocked on quote',
      prior: [{ id: 'ACT-0611', title: 'RDS reserved-instance commit', meta: 'saved 31% · 11mo ago' }],
    },
    conversation: [
      { author: 'Cloud spend monitor', role: 'requester', time: 'Jul 10', body: 'Compute spend anomaly: +34% MoM, sustained 3 weeks.' },
      { author: 'Finance agent', role: 'agent', time: 'Jul 10', body: 'Root cause is the inference cluster. Two of three pricing options quoted; TAM custom commit outstanding. Blocking until the picture is complete.' },
    ],
    discussion: [],
    brain: {
      reads: [
        { label: 'Spend trend', value: '+34% MoM · inference cluster', source: 'aws · 4h' },
        { label: 'Capacity plan', value: 'Phase-3 moves inference in-boundary Q4', source: 'world model · recall' },
        { label: 'Commit history', value: 'RDS RI saved 31%, no overrun', source: 'event log' },
        { label: 'Quotes', value: '2 of 3 in · TAM custom pending', source: 'email · 4h' },
      ],
      playbook: { id: 'PB-355', name: 'Cloud commit decision', origin: 'learned from 6 traces', success: '84% verified', steps: [
        { label: 'Attribute the spend delta', state: 'done' },
        { label: 'Gather all pricing options', state: 'current' },
        { label: 'Model against capacity plan', state: 'pending' },
        { label: 'Operator decision', state: 'pending' },
      ]},
      route: { model: 'Owned adapter A-7 (open weights)', path: 'in-boundary · customer VPC', reason: 'cost modeling on owned data — no disclosure needed', cost: '$0.003 / verified outcome', tokens: '4.2K tokens' },
      boundary: {
        sent: ['nothing crossed — in-boundary route'],
        withheld: ['spend data', 'capacity plan', 'vendor quotes'],
        provider: 'none — sovereign inference', retention: 'n/a · logged', ledger: 'LG-30492',
      },
      writes: [
        { on: 'Wait ↵', signal: 'reinforces complete-picture gating on commits' },
        { on: 'Variant ⌥1', signal: 'teaches rate-lock urgency weighting' },
        { on: 'Alternative ⌥2', signal: 'couples commit decisions to the Phase-3 plan' },
      ],
    },
  },
  {
    id: 'ACT-1055', tab: 'ACT-1055 Provision Jon…', dot: 'pending', domain: 'TechOps',
    title: 'Provision new hire Jonas B. — laptop, Okta, standard Eng bundle',
    summary: 'Jonas starts Monday. I can provision the standard Engineering bundle: Okta, GitHub, Slack, Jira, plus a MacBook from inventory, all from the role template.',
    hold: 'Confidence 94% — first run for this role template, held once.',
    path: ['TechOps agent', 'hibob', 'jonas berg', 'act-1055', 'awaiting you'],
    verb: 'APPROVE', verbKey: 'A', timer: '2d 20h', confidence: 94, state: 'needs', updated: '55m ago', updatedPct: 44, slaPct: 60, arrival: 9,
    quote: { initials: 'HR', name: 'People ops', via: 'HiBob', route: 'TechOps agent', status: 'waiting for you', body: 'New hire record complete: Jonas Berg, Senior Engineer, Platform, starts Monday. Standard provisioning requested.' },
    why: ['First execution of the updated Eng role template', 'Bundle includes production GitHub access', 'Device assignment pulls from low inventory (2 left)'],
    sources: '5 examined',
    sourcesDetail: ['hibob hire record · role template v3', 'inventory · okta group map · github teams'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Approve & provision the full bundle', desc: 'Template v3 matches 14 prior Platform hires; inventory reserved.', keys: '↵' },
      { kind: 'Variant', title: 'Provision accounts now, hold GitHub prod access for week 2.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Provision minimal set; manager picks extras day 1.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #okta · #jamf · #slack — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Hire', value: 'Jonas Berg · Senior Engineer', source: 'hibob' },
        { label: 'Team', value: 'Platform · manager Nadia Oye', source: 'hibob' },
        { label: 'Template', value: 'Eng role template v3', source: 'ragnar', extra: 'recall', tone: 'live' },
      ],
      roster: [
        { name: 'Jonas Berg', meta: 'Senior Engineer · starts Mon', tag: 'Subject', source: 'hibob' },
        { name: 'Nadia Oye', meta: 'Manager · Platform', source: 'okta' },
      ],
      devices: [{ name: 'MacBook Pro 16"', meta: 'P-511 · reserved from inventory', source: 'Iru' }],
      apps: [
        { name: 'Okta', meta: 'groups: eng, platform', source: 'Okta' },
        { name: 'GitHub', meta: 'teams: platform, ci', source: 'GitHub' },
      ],
      scope: 'Provision 6 systems · assign device · day-1 ready',
      prior: [{ id: 'ACT-0940', title: 'Platform hire provisioning (template v2)', meta: '14 runs · clean' }],
    },
    conversation: [
      { author: 'People ops', role: 'requester', time: 'Wed', body: 'Jonas Berg\u2019s record is complete — standard Eng provisioning for Monday, please.' },
      { author: 'TechOps agent', role: 'agent', time: 'Wed', body: 'Role template v3 is new this month, so its first execution is held for review. Everything else matches the last 14 Platform hires.' },
    ],
    discussion: [],
    brain: {
      reads: [
        { label: 'Hire record', value: 'Complete · start date Mon', source: 'hibob · 55m' },
        { label: 'Role template', value: 'v3 · first execution', source: 'world model · recall' },
        { label: 'Inventory', value: '2 MacBooks left · P-511 reserved', source: 'iru · 55m' },
        { label: 'Group map', value: 'Platform → 6 systems, 11 groups', source: 'world model · recall' },
      ],
      playbook: { id: 'PB-118', name: 'New hire provisioning', origin: 'learned from 41 traces', success: '97% verified', steps: [
        { label: 'Validate hire record', state: 'done' },
        { label: 'Resolve role template → systems', state: 'done' },
        { label: 'Reserve device', state: 'done' },
        { label: 'Provision accounts & groups', state: 'held' },
        { label: 'Verify day-1 checklist', state: 'pending' },
      ]},
      route: { model: 'Owned adapter A-3 (open weights)', path: 'in-boundary · customer VPC', reason: 'template resolution is deterministic-adjacent — owned route passes evals at 99%', cost: '$0.002 / verified outcome', tokens: '1.9K tokens' },
      boundary: {
        sent: ['nothing crossed — in-boundary route'],
        withheld: ['hire PII', 'org graph', 'system credentials'],
        provider: 'none — sovereign inference', retention: 'n/a · logged', ledger: 'LG-30495',
      },
      writes: [
        { on: 'Approve ↵', signal: 'template v3 validated → future runs auto-execute' },
        { on: 'Variant ⌥1', signal: 'teaches staged prod-access for new hires' },
        { on: 'Alternative ⌥2', signal: 'weakens template trust → v3 re-review' },
      ],
    },
  },
  {
    id: 'ACT-1057', tab: 'ACT-1057 Merge Miro wo…', dot: 'done', domain: 'Procurement',
    title: 'Merge duplicate Miro workspaces billed separately',
    summary: 'Design and Product have been paying for two Miro workspaces — $340/mo overlap. Merged under the Design contract, 22 boards migrated, Product workspace cancelled at period end.',
    hold: 'Handled — executed after your approval.',
    path: ['Procurement agent', 'netsuite', 'saas audit', 'act-1057', 'handled'],
    verb: 'DONE', verbKey: '', timer: '—', confidence: 96, state: 'handled', updated: 'yesterday', updatedPct: 10, slaPct: 100, arrival: 10,
    quote: { initials: 'SA', name: 'SaaS audit', via: 'NetSuite', route: 'Procurement agent', status: 'handled', body: 'Quarterly SaaS audit flagged two Miro workspaces with 60% member overlap, billed on separate cards.' },
    why: ['Cancellation is hard to reverse mid-period', 'Board migration risks losing shared links', 'Two budget owners affected'],
    sources: '4 examined',
    sourcesDetail: ['netsuite billing · miro admin exports', 'board inventory · owner sign-offs'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Merge under Design contract, cancel Product workspace', desc: 'Executed — 22 boards migrated, links preserved, $340/mo recovered.', keys: '↵' },
      { kind: 'Variant', title: 'Keep both, consolidate at renewal.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Escalate to both budget owners first.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #netsuite · #miro — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Overlap', value: '60% shared members · $340/mo', source: 'miro' },
        { label: 'Owners', value: 'Design + Product budget lines', source: 'netsuite' },
      ],
      roster: [
        { name: 'Design ops', meta: 'workspace owner · signed off', source: 'miro' },
        { name: 'Product ops', meta: 'workspace owner · signed off', source: 'miro' },
      ],
      devices: [],
      apps: [{ name: 'Miro', meta: 'merged · 22 boards migrated', source: 'Miro' }],
      scope: 'Merge workspaces · cancel one · $4.1K/yr recovered',
      prior: [{ id: 'ACT-0722', title: 'Duplicate Zoom licences cleanup', meta: 'recovered $6K/yr' }],
    },
    conversation: [
      { author: 'SaaS audit', role: 'requester', time: 'Jul 8', body: 'Duplicate detected: two Miro workspaces, 60% member overlap.' },
      { author: 'Procurement agent', role: 'agent', time: 'Jul 8', body: 'Both owners signed off on a merge. Cancellation is irreversible mid-period — held for approval, now executed.' },
    ],
    discussion: [],
    brain: {
      reads: [
        { label: 'Billing', value: 'Two workspaces · separate cards', source: 'netsuite' },
        { label: 'Member graph', value: '60% overlap · 41 shared users', source: 'miro' },
        { label: 'Sign-offs', value: 'Both owners confirmed in Slack', source: 'slack' },
      ],
      playbook: { id: 'PB-260', name: 'Duplicate SaaS merge', origin: 'learned from 8 traces', success: '92% verified', steps: [
        { label: 'Detect duplicate billing', state: 'done' },
        { label: 'Confirm owner sign-offs', state: 'done' },
        { label: 'Migrate boards & links', state: 'done' },
        { label: 'Cancel duplicate workspace', state: 'done' },
        { label: 'Verify savings land', state: 'current' },
      ]},
      route: { model: 'Owned adapter A-7 (open weights)', path: 'in-boundary · customer VPC', reason: 'audit + migration planning fully in-boundary', cost: '$0.003 / verified outcome', tokens: '3.8K tokens' },
      boundary: {
        sent: ['nothing crossed — in-boundary route'],
        withheld: ['billing data', 'member identities', 'board contents'],
        provider: 'none — sovereign inference', retention: 'n/a · logged', ledger: 'LG-30440',
      },
      writes: [
        { on: 'Approved ✓', signal: 'recorded — PB-260 reinforced · verified outcome: $4.1K/yr' },
      ],
    },
  },
  {
    id: 'ACT-1048', tab: 'ACT-1048 Refund Northw…', dot: 'done', domain: 'Finance',
    title: 'Credit $9,150 to Northwind for the March outage — refund approved',
    summary: 'Northwind\u2019s success manager requested an SLA credit for the March incident. Contract entitles them to 8%; I proposed $9,150 against Q1 fees. Approved and posted.',
    hold: 'Handled — executed after your approval.',
    path: ['Support agent', 'zendesk', 'northwind', 'act-1048', 'handled'],
    verb: 'DONE', verbKey: '', timer: '—', confidence: 90, state: 'handled', updated: '2d ago', updatedPct: 5, slaPct: 100, arrival: 11,
    quote: { initials: 'NW', name: 'Northwind CSM', via: 'Zendesk', route: 'Support agent', status: 'handled', body: 'Customer requested the contractual SLA credit for the March 12 outage. Entitlement verified against the signed MSA.' },
    why: ['Money movement to an external party', 'Contract interpretation involved', 'Customer-facing communication attached'],
    sources: '5 examined',
    sourcesDetail: ['MSA §9 SLA terms · incident report INC-88', 'zendesk thread · netsuite AR'],
    options: [
      { kind: "Recommended - agent's proposal", title: 'Approve $9,150 credit against Q1 fees', desc: 'Executed — credit memo posted, customer notified through Zendesk.', keys: '↵' },
      { kind: 'Variant', title: 'Offer service credits instead of cash credit.', keys: ['⌥', '1'] },
      { kind: 'Alternative', title: 'Escalate to the account exec for a retention bundle.', keys: ['⌥', '2'] },
    ],
    via: 'Act via #netsuite · #zendesk — or @ragnar, /commands — type to act',
    context: {
      identity: [
        { label: 'Customer', value: 'Northwind · $114K ARR', source: 'netsuite' },
        { label: 'Entitlement', value: 'MSA §9: 8% monthly fee credit', source: 'ragnar', extra: 'recall', tone: 'live' },
      ],
      roster: [
        { name: 'Northwind CSM', meta: 'requested the credit', source: 'zendesk' },
      ],
      devices: [],
      apps: [{ name: 'NetSuite', meta: 'credit memo CM-2291 posted', source: 'NetSuite' }],
      scope: 'Credit $9,150 · Q1 fees · customer notified',
      prior: [{ id: 'INC-88', title: 'March 12 outage · 4h11m', meta: 'postmortem closed' }],
    },
    conversation: [
      { author: 'Northwind CSM', role: 'requester', time: 'Jul 11', body: 'Requesting the contractual SLA credit for the March 12 outage per MSA §9.' },
      { author: 'Support agent', role: 'agent', time: 'Jul 11', body: 'Entitlement verified: 4h11m outage crosses the 99.9% threshold. Calculated $9,150. External money movement — held for approval, now posted.' },
    ],
    discussion: [],
    brain: {
      reads: [
        { label: 'MSA terms', value: '§9: 8% credit past 99.9% breach', source: 'contract · recall' },
        { label: 'Incident record', value: 'INC-88 · 4h11m · confirmed', source: 'event log' },
        { label: 'AR state', value: 'Q1 invoice paid · credit applicable', source: 'netsuite' },
      ],
      playbook: { id: 'PB-390', name: 'SLA credit fulfillment', origin: 'learned from 5 traces', success: '90% verified', steps: [
        { label: 'Verify entitlement vs MSA', state: 'done' },
        { label: 'Compute credit amount', state: 'done' },
        { label: 'Post credit memo', state: 'done' },
        { label: 'Notify customer', state: 'done' },
      ]},
      route: { model: 'Claude Sonnet', path: 'GCP Vertex · europe-west4', reason: 'contract interpretation — frontier route on legal-text class', cost: '$0.13 / verified outcome', tokens: '16.7K tokens' },
      boundary: {
        sent: ['SLA clause excerpt · amounts', 'incident duration', 'decision request: approve credit'],
        withheld: ['customer identity', 'full MSA', 'ARR & account data'],
        provider: 'Anthropic via Vertex — lab never sees traffic', retention: 'zero-retention posture · logged', ledger: 'LG-30402',
      },
      writes: [
        { on: 'Approved ✓', signal: 'recorded — PB-390 reinforced · entitlement parser promoted' },
      ],
    },
  },
];

/* Lifecycle table — clay-style records, one agent-enriched column per entity type. */
export const LIFECYCLE = {
  Employees: {
    cols: [
      { label: 'Employee', source: 'hibob', flex: 1.4 },
      { label: 'Role · team', source: 'okta', flex: 1.3 },
      { label: 'Device', source: 'iru', flex: 1.2 },
      { label: 'Access', source: 'okta', flex: 1.1 },
      { label: 'Stage', source: 'lifecycle', flex: 0.9 },
      { label: 'Risk signals', source: 'agent', agent: true, flex: 1.6 },
    ],
    rows: [
      [{ v: 'Priya Nair', m: 'since May 2024' }, { v: 'Software Engineer', m: 'Engineering' }, { v: 'P-442 · MacBook 14"', m: 'compliant · migrated today' }, { v: 'Eng standard', m: '6 systems' }, { v: 'Active' }, { v: 'Unlock pending · ACT-1049', m: 'MFA re-enrolled 07:44' }],
      [{ v: 'Jonas Berg', m: 'starts Monday' }, { v: 'Senior Engineer', m: 'Platform' }, { v: 'P-511 · reserved', m: 'imaging queued' }, { v: 'Eng template v3', m: 'first run' }, { v: 'Onboarding' }, { v: 'Provisioning held · ACT-1055', m: 'template v3 first execution' }],
      [{ v: 'Tomas V.', m: 'contractor' }, { v: 'Contractor', m: 'departed Friday' }, { v: 'P-104 · ThinkPad X1', m: 'not returned' }, { v: 'GitHub org + PAT', m: 'still live' }, { v: 'Offboarding' }, { v: 'Credential residue · ACT-1053', m: 'revoke + key rotation held' }],
      [{ v: 'Marta Kline', m: 'since 2022' }, { v: 'Brand Lead', m: 'Marketing' }, { v: 'P-238 · MacBook 14"', m: 'compliant' }, { v: 'Marketing bundle', m: '4 systems' }, { v: 'Active' }, { v: 'Guest grant open · ACT-1050', m: 'Studio Norr · expiring' }],
      [{ v: 'Nadia Oye', m: 'since 2021' }, { v: 'EM', m: 'Platform' }, { v: 'P-301 · MacBook 16"', m: 'compliant' }, { v: 'Eng standard + approvals' }, { v: 'Active' }, { v: '2 open requests', m: 'offsite exception · Linear pilot' }],
      [{ v: 'Leah Chen', m: 'since 2020' }, { v: 'Eng Manager', m: 'Engineering' }, { v: 'P-198 · MacBook 14"', m: 'compliant' }, { v: 'Eng standard + approvals' }, { v: 'Active' }, { v: 'No signals', m: 'clean 90 days' }],
    ],
  },
  Devices: {
    cols: [
      { label: 'Device', source: 'iru', flex: 1.4 },
      { label: 'Assignee', source: 'okta', flex: 1.1 },
      { label: 'Posture', source: 'iru', flex: 1.1 },
      { label: 'Warranty', source: 'vendor', flex: 0.9 },
      { label: 'Stage', source: 'lifecycle', flex: 0.9 },
      { label: 'Refresh & risk', source: 'agent', agent: true, flex: 1.6 },
    ],
    rows: [
      [{ v: 'P-442 · MacBook Pro 14"' }, { v: 'Priya Nair' }, { v: 'Compliant', m: 'posture 07:41' }, { v: 'Mar 2027' }, { v: 'Active' }, { v: 'Posture verified today', m: 'migration clean' }],
      [{ v: 'P-511 · MacBook Pro 16"' }, { v: 'Jonas Berg', m: 'reserved' }, { v: 'Imaging queued' }, { v: 'Jan 2028' }, { v: 'Provisioning' }, { v: 'Day-1 checklist pending', m: 'ACT-1055' }],
      [{ v: 'P-104 · ThinkPad X1' }, { v: 'Tomas V.', m: 'departed' }, { v: 'Unmanaged', m: 'last seen Fri' }, { v: 'expired' }, { v: 'Retiring' }, { v: 'Return overdue 3 days', m: 'escalation drafted' }],
      [{ v: 'P-238 · MacBook Pro 14"' }, { v: 'Marta Kline' }, { v: 'Compliant' }, { v: 'Aug 2026' }, { v: 'Active' }, { v: 'Refresh due in 13 mo', m: 'battery 87%' }],
      [{ v: 'P-390 · MacBook Air' }, { v: 'Unassigned', m: 'inventory' }, { v: 'Sealed' }, { v: 'Nov 2026' }, { v: 'In stock' }, { v: 'Low stock — 2 left in tier', m: 'reorder point hit' }],
    ],
  },
  Vendors: {
    cols: [
      { label: 'Vendor', source: 'netsuite', flex: 1.2 },
      { label: 'Owner', source: 'okta', flex: 1.0 },
      { label: 'Contract', source: 'netsuite', flex: 1.0 },
      { label: 'Spend', source: 'netsuite', flex: 0.8 },
      { label: 'Stage', source: 'lifecycle', flex: 1.0 },
      { label: 'Renewal posture', source: 'agent', agent: true, flex: 1.8 },
    ],
    rows: [
      [{ v: 'Studio Norr' }, { v: 'Marta Kline' }, { v: 'through Jul 31' }, { v: '$46K/yr' }, { v: 'Active' }, { v: 'CO-112 reconciled · payment held', m: 'ACT-1052' }],
      [{ v: 'Zendesk' }, { v: 'Sam Ruiz' }, { v: 'renews Jul 26' }, { v: '$71K/yr' }, { v: 'Renewal window' }, { v: 'True-down to 78 seats · −$31K/yr', m: 'counter drafted · ACT-1051' }],
      [{ v: 'Atlassian' }, { v: 'Tooling council' }, { v: '14 mo left' }, { v: '$14.4K/yr' }, { v: 'Active' }, { v: 'Platform usage −40% QoQ', m: 'consolidation watch' }],
      [{ v: 'Linear' }, { v: 'Nadia Oye' }, { v: 'pilot pending' }, { v: '$2.9K/90d' }, { v: 'Security review' }, { v: 'SOC2 Type II verified', m: 'pilot gate held · ACT-1054' }],
      [{ v: 'AWS' }, { v: 'Infra team' }, { v: 'monthly' }, { v: '$41K/mo' }, { v: 'Active' }, { v: 'Savings plan blocked on TAM quote', m: 'ACT-1058' }],
    ],
  },
  Applications: {
    cols: [
      { label: 'Application', source: 'okta', flex: 1.1 },
      { label: 'Seats', source: 'usage', flex: 1.2 },
      { label: 'Owner', source: 'okta', flex: 1.0 },
      { label: 'Renewal', source: 'netsuite', flex: 0.9 },
      { label: 'Stage', source: 'lifecycle', flex: 0.9 },
      { label: 'Consolidation signal', source: 'agent', agent: true, flex: 1.7 },
    ],
    rows: [
      [{ v: 'Okta' }, { v: '312 licensed · 298 active' }, { v: 'IT' }, { v: 'Feb 2027' }, { v: 'Active' }, { v: '1 unlock held', m: 'ACT-1049' }],
      [{ v: 'GitHub' }, { v: '141 · 139 active' }, { v: 'Platform' }, { v: 'Dec 2026' }, { v: 'Active' }, { v: '1 stale credential', m: 'revoke held · ACT-1053' }],
      [{ v: 'Zendesk' }, { v: '120 · 78 active' }, { v: 'Sam Ruiz' }, { v: 'Jul 26' }, { v: 'Renewal' }, { v: '42 idle seats', m: 'true-down counter ready' }],
      [{ v: 'Figma' }, { v: '84 · 61 active' }, { v: 'Design ops' }, { v: 'Oct 2026' }, { v: 'Active' }, { v: '2 guest seats free', m: 'agency policy gap flagged' }],
      [{ v: 'Miro' }, { v: '96 · 88 active' }, { v: 'Design ops' }, { v: 'May 2027' }, { v: 'Consolidated' }, { v: 'Duplicate merged · $4.1K/yr back', m: 'verified' }],
    ],
  },
};

/* Library — skills and company-brain stats (playbooks derive from CASES). */
export const LIBRARY = {
  skills: [
    { name: 'Identity verification', meta: 'record ↔ device ↔ requester match', uses: '104 runs · 99% verified' },
    { name: 'Three-way match', meta: 'invoice ↔ PO ↔ receipt reconciliation', uses: '58 runs · 93% verified' },
    { name: 'Blast-radius mapping', meta: 'what breaks if this credential dies', uses: '47 runs · 98% verified' },
    { name: 'Access scoping', meta: 'least-privilege grant drafting', uses: '34 runs · 96% verified' },
    { name: 'Policy exception framing', meta: 'delta, precedent, one-time tags', uses: '34 runs · 89% verified' },
    { name: 'Renewal counter drafting', meta: 'usage-based true-down terms', uses: '12 runs · 91% verified' },
  ],
  brain: [
    { label: 'Entities tracked', value: '2,340', meta: 'people · devices · vendors · apps' },
    { label: 'Playbooks', value: '412', meta: 'learned from traces · zero hand-written' },
    { label: 'Decision traces', value: '11,204', meta: 'training signals recorded' },
    { label: 'Eval cases', value: '388', meta: 'PerkBench · replayed nightly' },
  ],
};
